"use client";

import React, { useState } from "react";
import Link from "next/link";
import {
  HelpCircle,
  CreditCard,
  Headphones,
  ShieldCheck,
  Plus,
  Minus,
  ArrowRight,
} from "lucide-react";

type FAQCategory = "general" | "voice" | "pricing" | "privacy";

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ_DATA: Record<
  FAQCategory,
  {
    label: string;
    icon: React.ElementType;
    items: FAQItem[];
  }
> = {
  general: {
    label: "GENERAL",
    icon: HelpCircle,
    items: [
      {
        question:
          "HOW DOES READORA CONVERT DOCUMENTS INTO VOICE CONVERSATIONS?",
        answer:
          "Readora uses semantic document parsing and vector search to index your uploaded PDFs, books, and study notes. When you speak, our voice AI retrieves the exact relevant context and generates natural, spoken answers with real-time speech synthesis.",
      },
      {
        question: "WHICH FILE FORMATS AND SIZES ARE SUPPORTED?",
        answer:
          "Currently, Readora supports PDF documents, research papers, reports, and textbooks up to 50MB. Text content is automatically extracted, segmented by page, and indexed for instant semantic retrieval.",
      },
      {
        question: "HOW ACCURATE ARE THE CITED REFERENCES?",
        answer:
          "Every response generated by Readora references verified chapter sections and exact page numbers from your original upload, allowing you to cross-check sources and read with zero hallucinations.",
      },
      {
        question: "CAN I ACCESS MY SAVED SESSIONS ACROSS DIFFERENT DEVICES?",
        answer:
          "Yes. Once you sign in with your account, your personal document shelf, voice preferences, and full conversation transcripts are securely synchronized across desktop, tablet, and mobile browsers.",
      },
    ],
  },
  voice: {
    label: "VOICE & AI",
    icon: Headphones,
    items: [
      {
        question: "WHICH AI VOICE PERSONAS ARE AVAILABLE?",
        answer:
          "Readora features three expressive voice companions: Ahmed Ali Khan (Gentle & Reflective), Sarah Ali Shah (Analytical & Engaging), and Umar Khan (Concise & Academic). You can assign different personas to each document.",
      },
      {
        question: "CAN I INTERRUPT THE VOICE ASSISTANT WHILE IT'S SPEAKING?",
        answer:
          "Yes! With our conversational turn-taking pipeline, you can speak at any moment to pause the assistant, ask follow-up questions, or steer the conversation in a new direction naturally.",
      },
      {
        question: "WHAT IS THE AVERAGE VOICE RESPONSE LATENCY?",
        answer:
          "Our speech-to-speech architecture achieves sub-second latency (under 500ms), giving you the feel of an effortless, real-time voice call rather than a delayed chatbot.",
      },
    ],
  },
  pricing: {
    label: "PRICING & PLANS",
    icon: CreditCard,
    items: [
      {
        question: "WHAT IS INCLUDED IN THE FREE PLAN?",
        answer:
          "The Free plan allows you to upload documents, test all 3 voice personas, and explore interactive voice Q&A sessions with standard monthly conversation allowances without requiring a credit card.",
      },
      {
        question: "WHAT DO PRO AND STANDARD SUBSCRIPTIONS UNLOCK?",
        answer:
          "Paid tiers unlock expanded document shelf capacity, longer continuous session durations, prioritized vector indexing, and increased voice conversation minutes.",
      },
      {
        question: "CAN I CANCEL OR UPGRADE MY PLAN AT ANY TIME?",
        answer:
          "Yes, you can upgrade, downgrade, or cancel your subscription at any time from your account settings. Billing adjustments and prorations are handled securely via Clerk & Stripe.",
      },
    ],
  },
  privacy: {
    label: "PRIVACY & SECURITY",
    icon: ShieldCheck,
    items: [
      {
        question: "IS MY UPLOADED DOCUMENT DATA SAFE AND PRIVATE?",
        answer:
          "Yes. Your uploaded files and audio transcripts are encrypted in transit and at rest. We never use your proprietary research, books, or personal notes to train public AI foundation models.",
      },
      {
        question: "CAN I DELETE MY UPLOADED DOCUMENTS AND TRANSCRIPTS?",
        answer:
          "You have total control over your library. Deleting any book or document from your dashboard permanently purges its vector embeddings and conversation transcripts.",
      },
    ],
  },
};

export default function FAQSection() {
  const [activeCategory, setActiveCategory] = useState<FAQCategory>("general");
  const [openIndexes, setOpenIndexes] = useState<number[]>([0]); // First item open by default

  const toggleAccordion = (index: number) => {
    setOpenIndexes((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index],
    );
  };

  const handleCategoryChange = (cat: FAQCategory) => {
    setActiveCategory(cat);
    setOpenIndexes([0]); // Open first item of new category
  };

  const currentCategoryData = FAQ_DATA[activeCategory];

  return (
    <section id="faq" className="w-full mb-16 scroll-mt-24">
      <div className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-card)] p-6 sm:p-10 lg:p-12">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12">
          {/* Left Column: Title, Category Tabs, Support Box */}
          <div className="lg:col-span-4 flex flex-col justify-between">
            <div>
              <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-[var(--text-primary)] uppercase">
                NEED HELP?
              </h2>
              <p className="mt-3 text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed font-medium">
                Can&apos;t find what you&apos;re looking for? Reach out to our
                support team for personal assistance.
              </p>

              {/* Category Tabs */}
              <div className="mt-8 flex flex-col gap-2">
                {(Object.keys(FAQ_DATA) as FAQCategory[]).map((catKey) => {
                  const category = FAQ_DATA[catKey];
                  const Icon = category.icon;
                  const isActive = activeCategory === catKey;

                  return (
                    <button
                      key={catKey}
                      onClick={() => handleCategoryChange(catKey)}
                      className={`w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-xs sm:text-sm font-bold tracking-wider uppercase transition-colors duration-150 cursor-pointer text-left ${
                        isActive
                          ? "bg-[var(--text-primary)] text-white shadow-none"
                          : "text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-primary)]"
                      }`}
                    >
                      <Icon
                        className={`h-4 w-4 ${
                          isActive
                            ? "text-white"
                            : "text-[var(--text-secondary)]"
                        }`}
                      />
                      <span>{category.label}</span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Support Callout Box */}
            <div className="mt-8 rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-primary)] p-5 sm:p-6">
              <p className="text-xs sm:text-sm font-bold tracking-wider text-[var(--text-primary)] uppercase">
                STILL HAVE QUESTIONS?
              </p>
              <p className="mt-1 text-[11px] font-semibold text-[var(--text-secondary)] uppercase tracking-wider">
                RESPONSE UNDER 12 HOURS
              </p>
              <Link
                href="/contact"
                className="mt-4 flex items-center justify-center gap-2 w-full rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-card)] hover:bg-[var(--bg-secondary)] px-4 py-3 text-xs font-bold text-[var(--text-primary)] uppercase tracking-wider transition-colors duration-150 text-center"
              >
                <span>CONTACT SUPPORT</span>
                <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </div>
          </div>

          {/* Right Column: Accordion FAQ List */}
          <div className="lg:col-span-8 flex flex-col gap-3 sm:gap-4">
            {currentCategoryData.items.map((item, index) => {
              const isOpen = openIndexes.includes(index);

              return (
                <div
                  key={item.question}
                  className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--bg-primary)] transition-colors duration-150 overflow-hidden"
                >
                  <button
                    onClick={() => toggleAccordion(index)}
                    aria-expanded={isOpen}
                    className="w-full flex items-center justify-between gap-4 p-5 sm:p-6 text-left cursor-pointer select-none"
                  >
                    <span className="font-bold text-xs sm:text-sm text-[var(--text-primary)] tracking-wide uppercase leading-snug">
                      {item.question}
                    </span>
                    <div className="flex items-center justify-center h-8 w-8 rounded-full border border-[var(--border-subtle)] bg-[var(--bg-card)] text-[var(--text-primary)] shrink-0">
                      {isOpen ? (
                        <Minus className="h-4 w-4" />
                      ) : (
                        <Plus className="h-4 w-4" />
                      )}
                    </div>
                  </button>

                  {isOpen && (
                    <div className="px-5 pb-5 sm:px-6 sm:pb-6 pt-0 border-t border-[var(--border-subtle)]/60">
                      <p className="mt-4 text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed">
                        {item.answer}
                      </p>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
